import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {createDiscovery} from '../dist/discovery.mjs';
import {createThread} from '../dist/thread.mjs';
import {createServer} from './server.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url),'utf8'));
const corpus=read('../dist/corpus.json'),model=read('../dist/model.json'),provenance=read('../dist/provenance.json');
assert.ok(corpus.length>=50);assert.equal(new Set(corpus.map(r=>r.registry)).size,corpus.length);assert.equal(corpus.filter(r=>r.connectionType==='explicit').length,8);
for(const r of corpus){assert.equal(r.review.jesusExplicit,r.connectionType==='explicit');if(r.review.jesusExplicit)assert.match(r.text,/\bJesus\b/i);assert.ok(!r.intense);assert.ok(!/\b(suicide|strangulation|rape|blood|stabbed|hell|satan)\b/i.test(r.text));assert.ok(provenance.sources.some(s=>s.url===r.source));assert.equal(createHash('sha256').update(r.text).digest('hex'),r.textHash)}
const d=createDiscovery(corpus,model);const loved=d.recommend('I want to feel loved and accepted.');assert.ok(loved.length>1);assert.ok(loved.every(r=>corpus.some(c=>c.id===r.id)));assert.ok(d.recommend('I am looking for hope and a second chance.')[0].themes.some(t=>['Hope','Second chances'].includes(t)));assert.ok(d.recommend('I want to reflect on my choices and purpose.')[0].themes.some(t=>['Reflection','Purpose','Choices'].includes(t)));const seen=new Set();for(let i=0;i<10;i++){const r=d.recommend('I want to feel loved and accepted.')[0];seen.add(r.id);d.markShown(r.id)}assert.ok(seen.size>=6);assert.ok(d.recommend('An encounter with Jesus').every(r=>r.connectionType==='explicit'));assert.ok(loved.every(r=>!r.matchExplanation.includes('undefined')));for(const prompt of ['quantum computing qubits','hi','?','!!!','zzxxqv']){const fallback=d.recommend(prompt);assert.ok(fallback.length>0);assert.ok(fallback.every(r=>corpus.some(c=>c.id===r.id)));assert.ok(fallback[0].looseMatch);}assert.throws(()=>d.recommend(''));for(const prompt of ['love','family','acceptance','hope and second chance','Jesus','quantum computing']){const rs=d.recommend(prompt);assert.ok(rs.length>=1&&rs.length<=5);assert.equal(new Set(rs.map(x=>x.registry)).size,rs.length);assert.ok(rs.every(x=>!x.matchExplanation.includes('loose match')))}const fresh=createDiscovery(corpus,model);assert.equal(fresh.recommend('family').length,2);assert.equal(fresh.recommend('acceptance').length,3);assert.equal(fresh.recommend('hope and second chance').length,1);
const happy=createDiscovery(corpus,model);const happyFirst=happy.recommend('happy');happy.markShown(happyFirst[0].id);const happySecond=happy.recommend('happy');assert.equal(happyFirst.length,happySecond.length);assert.notEqual(happyFirst[0].id,happySecond[0].id);
const conversation=createThread();const first=conversation.append('happy',happyFirst);const second=conversation.append('hope',d.recommend('hope and second chance'));assert.equal(conversation.entries.length,2);assert.equal(conversation.get(first.id).query,'happy');conversation.select(first.id,1);assert.equal(conversation.get(first.id).position,1);assert.equal(conversation.get(second.id).position,0);const third=conversation.append('happy',happySecond);assert.equal(third.id,3);assert.equal(conversation.get(first.id).position,1);assert.equal(conversation.get(first.id).results[0].id,happyFirst[0].id);assert.throws(()=>conversation.select(first.id,99));assert.equal(createThread().entries.length,0);
const app=fs.readFileSync(new URL('../dist/app.mjs',import.meta.url),'utf8');assert.ok(app.includes('Read the original account'));assert.ok(app.includes('View the source list'));assert.ok(app.includes('Shared by'));
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.ok(!html.includes('benchmark'));assert.ok(html.includes('Next')===false);assert.ok(html.includes('id="prompt"'));assert.ok(html.includes('id="welcome"'));assert.ok(html.includes('id="reading" hidden'));
const server=await createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
try{assert.equal((await fetch(origin+'/health')).status,200);const response=await fetch(origin+'/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:'love and acceptance'})});assert.equal(response.status,200);const result=await response.json();assert.ok(result.results.every(r=>corpus.some(c=>c.id===r.id)));assert.equal((await fetch(origin+'/api/search',{method:'POST',headers:{'content-type':'application/json'},body:'{"query":4}'})).status,400);for(const file of ['index.html','style.css','app.mjs','discovery.mjs','thread.mjs','paper-grain.svg','engine.mjs','corpus.json','model.json','provenance.json'])assert.equal((await fetch(origin+'/'+file)).status,200);assert.equal((await fetch(origin+'/evaluation.json')).status,404)}finally{await new Promise(resolve=>server.close(resolve))}
console.log('PASS: 60-account scope, accurate Jesus labels, recommendation variety, stable repeated-prompt counts, retained thread navigation, reviewed text scope, source hashes, curated recommendations, changed prompt relevance, unsupported topics, API input validation, and static assets.');
